### ISSUE TITLE
A wall appears and disappears

### ISSUE THREAD

**Issue by mizquierdo97** [Project3CITM/CulverinEngine-Project3#120]
- Status

New

- Category (Gamplay, animation, scripting, particles, physics,...)
Render

- Description (Explain with detail the issue)
Lvl 1-1 One wall appears and disappears

- Steps to reproduce (Explain the exact steps to reproduce this issue)
Go to lvl 1-1. Two steps forward & 2 steps right

- Priority (P1:Critical, P2:High, P3:Medium, P4;Low)
P4

- Screenshot
![image](https://user-images.githubusercontent.com/14962939/39914924-b41addae-5506-11e8-8374-819c187d0dd7.png)

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by PereRifa** [comment]
Fixed.
