### ISSUE TITLE
Artifatcs in collision particles

### ISSUE THREAD

**Issue by carcasanchez** [Project3CITM/CulverinEngine-Project3#183]
- Status

New

- Category: Particles

- Description
Some artifacts (such as slashes) appear in collision particles (specially, arrow ones)

- Steps to reproduce (Explain the exact steps to reproduce this issue)
*Go to level 1_1
*Shoot the triple arrow to one wall while standing in front of it

- Priority: Low

- Screenshot
![imagen](https://user-images.githubusercontent.com/14940964/39917593-630b772c-550e-11e8-9854-610c3476da66.png)

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by Jordior97** [comment]
Solved
