### ISSUE TITLE
Crash at play/stop

### ISSUE THREAD

**Issue by Yulna** [Project3CITM/CulverinEngine-Project3#4]
- Status
New

- Category (Gamplay, animation, scripting, particles, physics,...)
Engine

- Description (Explain with detail the issue)
It crashes after playing, just one cube

- Steps to reproduce (Explain the exact steps to reproduce this issue)
 Create a cube, click in the play button and then click again to stop the game

- Priority (P1:Critical, P2:High, P3:Medium, P4;Low)
P1

- Screenshot
![image](https://user-images.githubusercontent.com/17148003/36266696-64112470-1272-11e8-9de6-406135b7a8a5.png)
![image](https://user-images.githubusercontent.com/17148003/36266712-7088aea8-1272-11e8-940a-a80d7e9d4805.png)

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by Yulna** [comment]
Update: You need to import one script for it to happen.

**Comment by elliotjb** [comment]
Solved.
