### ISSUE TITLE
Torch on banner

### ISSUE THREAD

**Issue by SrPerso** [Project3CITM/CulverinEngine-Project3#63]
- Status

New

- Category (Gamplay, animation, scripting, particles, physics,...)

Grafic/level design

- Description (Explain with detail the issue)

hay una antorcha encima de un estandarte

- Steps to reproduce (Explain the exact steps to reproduce this issue)

llegas akl segundo puzzle hacia la izquierda, llegar al puzzle y mirar a la izquierda ( LVL 2

- Priority (P1:Critical, P2:High, P3:Medium, P4;Low)

 P3

- Screenshot

https://gyazo.com/01236a16f7cfa5e5aa4e828205444e71

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by Yulna** [comment]
Go to the first fountain in lvl 2 and then to the left, the banner is on the opposite side of the puzzle lever
