### ISSUE TITLE
The player dead on the first puzzle

### ISSUE THREAD

**Issue by SrPerso** [Project3CITM/CulverinEngine-Project3#64]
- Status

New

- Category (Gamplay, animation, scripting, particles, physics,...)

script (?)

- Description (Explain with detail the issue)

el player se cesplaza a dos tiles del 

- Steps to reproduce (Explain the exact steps to reproduce this issue)

ir al puzzle y tirarte hacia atras en una tile que no toca

- Priority (P1:Critical, P2:High, P3:Medium, P4;Low)

P4

- Screenshot

https://gyazo.com/5d47ed25ba7e4f88b618650feaa967ad

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by Jordior97** [comment]
Era por el collider de la espada de jaime, que colisionaba con el collider del player, y como es kinematic, hacia que el player se desplazara hacia la derecha
