### ISSUE TITLE
Loading scripts Crash

### ISSUE THREAD

**Issue by Jordior97** [Project3CITM/CulverinEngine-Project3#7]
- Status

New

- Category (Gamplay, animation, scripting, particles, physics,...)

Scripting

- Description (Explain with detail the issue)

When creating/importing a script. If we close the engine and open it again, it crashes when it tries to read the script.

- Steps to reproduce (Explain the exact steps to reproduce this issue)

1) Create/Import a script.
2) Close the engine.
3) Open the engine.

- Priority (P1:Critical, P2:High, P3:Medium, P4;Low)

P1: Critical.

- Screenshot

![](https://i.gyazo.com/3328b26de4154c60c11deb8453ace348.png)

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by elliotjb** [comment]
Fixed. https://github.com/Project3CITM/CulverinEngine-Project3/commit/f0df2bec212010599b30cbae592261c55b57fe07
