### ISSUE TITLE
Flying fire

### ISSUE THREAD

**Issue by Yulna** [Project3CITM/CulverinEngine-Project3#87]
- Status

New

- Category (Gamplay, animation, scripting, particles, physics,...)
Gameplay

- Description (Explain with detail the issue)
When playing deanerys in a barrel puzzle deanerys can place a wall of fire in a barrel block, if hte arrel  block is sinking the fire wall will remain in the air.

- Steps to reproduce (Explain the exact steps to reproduce this issue)
Activata a barrel puzzle, wait until the barrels are about to sink, use the daenerys wall of fire skill.

- Priority (P1:Critical, P2:High, P3:Medium, P4;Low)
P2

- Screenshot

![image](https://user-images.githubusercontent.com/17148003/39354599-281d1d04-4a0b-11e8-9b11-ee7c7a29fa1b.png)

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by Jordior97** [comment]
Now you can't cast a firewall on the valyrian fire
