### ISSUE TITLE
Torch particles dissapears too soon

### ISSUE THREAD

**Issue by HeladodePistacho** [Project3CITM/CulverinEngine-Project3#96]
- Status

New

- Category (Gamplay, animation, scripting, particles, physics,...)

Particles

- Description (Explain with detail the issue)

For example Torch fire Particles disappears when i walk away from them, but Im still able to see the torch

- Steps to reproduce (Explain the exact steps to reproduce this issue)

Find a Torch and walk away while looking at it

- Priority (P1:Critical, P2:High, P3:Medium, P4;Low)

Medium

- Screenshot

- Annex:

If you do not know what to put in one of the sections or whant to know more about the QA workflow, access the following link:
https://docs.google.com/document/d/14ptI3YJ2dVoYKWJplgXgIlCXABCUqtt3bDMPxxyA6AY/edit?usp=sharing

**Comment by SrPerso** [comment]
#86
